/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is generated by TanStack Router.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotoToPrintRouteImport } from './routes/photostoprint'
import { Route as AdminRouteImport } from './routes/admin'

const IndexRoute = IndexRouteImport.update({ id:'/', path:'/', getParentRoute:()=>rootRouteImport } as any)
const PhotoToPrintRoute = PhotoToPrintRouteImport.update({ id:'/photostoprint', path:'/photostoprint', getParentRoute:()=>rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id:'/admin', path:'/admin', getParentRoute:()=>rootRouteImport } as any)

export interface FileRoutesByFullPath { '/':typeof IndexRoute; '/photostoprint':typeof PhotoToPrintRoute; '/admin':typeof AdminRoute }
export interface FileRoutesByTo { '/':typeof IndexRoute; '/photostoprint':typeof PhotoToPrintRoute; '/admin':typeof AdminRoute }
export interface FileRoutesById { __root__:typeof rootRouteImport; '/':typeof IndexRoute; '/photostoprint':typeof PhotoToPrintRoute; '/admin':typeof AdminRoute }
export interface FileRouteTypes { fileRoutesByFullPath:FileRoutesByFullPath; fullPaths:'/'|'/photostoprint'|'/admin'; fileRoutesByTo:FileRoutesByTo; to:'/'|'/photostoprint'|'/admin'; id:'__root__'|'/'|'/photostoprint'|'/admin'; fileRoutesById:FileRoutesById }
export interface RootRouteChildren { IndexRoute:typeof IndexRoute; PhotoToPrintRoute:typeof PhotoToPrintRoute; AdminRoute:typeof AdminRoute }
declare module '@tanstack/react-router' { interface FileRoutesByPath {
  '/':{id:'/';path:'/';fullPath:'/';preLoaderRoute:typeof IndexRouteImport;parentRoute:typeof rootRouteImport}
  '/photostoprint':{id:'/photostoprint';path:'/photostoprint';fullPath:'/photostoprint';preLoaderRoute:typeof PhotoToPrintRouteImport;parentRoute:typeof rootRouteImport}
  '/admin':{id:'/admin';path:'/admin';fullPath:'/admin';preLoaderRoute:typeof AdminRouteImport;parentRoute:typeof rootRouteImport}
}}
const rootRouteChildren:RootRouteChildren={IndexRoute,PhotoToPrintRoute,AdminRoute}
export const routeTree=rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr:true; router:Awaited<ReturnType<typeof getRouter>>; config:Awaited<ReturnType<typeof startInstance.getOptions>> } }
